### ISSUE TITLE
Would you consider a license change?

### ISSUE THREAD

**Issue by SStorm** [fflewddur/hola#4]
Great project, probably the only mDNS library in Java that actually works as advertised. However... GPL somewhat restricts the usage for commercial purposes - would you consider changing the license to Apache or similar, or did you have licensing in mind for the future?

Cheers!
Roman

**Comment by fflewddur** [comment]
Thanks! Yeah, I'm actually considering changing to the MIT license to encourage broader adoption, but I'm still trying to think this through.

**Comment by itsjohno** [comment]
Have you had any more thoughts related to changing the license?

**Comment by jconlon** [comment]
Have you decided yet.  MIT would be good.

**Comment by cschneider** [comment]
Communities like apache and eclipse have strict license policies that forbid using any GPL libs. So using such a strong copyleft license it is impossible to use your software in these projects.
As an example see https://www.apache.org/legal/resolved.html

**Comment by fflewddur** [comment]
I just migrated Hola to the MIT license. I'm currently getting my code signing certificate renewed; once that's done, I'll get a new package uploaded to Maven.
