### ISSUE TITLE
Is possible to define the network interface (Question)

### ISSUE THREAD

**Issue by aabf** [fflewddur/hola#5]
Hello,

Is possible to define the network interface where we want to search the Instances(mdns)?

Thanks

**Comment by fflewddur** [comment]
Yes, this is already supported via the Query.runOnceOn() method.

**Comment by aabf** [comment]
@fflewddur 
Sorry, I was using the version in maven repository and in there that function doesn't exist.
Can you update the maven?

**Comment by fflewddur** [comment]
Ack, sorry about that. I'll get an updated release pushed as soon as I can
:)

**Comment by aabf** [comment]
Thanks :-) When you update the maven can you tell me? Thanks

**Comment by fflewddur** [comment]
Sorry it took so long, but I just updated maven.

**Comment by aabf** [comment]
No problem. :-)

Thank you very much
